# Generated by Django 2.2.24 on 2021-11-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20211121_1706'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='Autor',
        ),
    ]
